version: "3"

services:
  server:
    image: sakuexe/server-image
    networks:
      - teht1network
    volumes:
      - servervol:/serverdata
    container_name: server

  client:
    image: sakuexe/client-image
    networks:
      - teht1network
    volumes:
      - clientvol:/clientdata
    container_name: client
    command: ["sh", "-c", "sleep 5 && node index.js"]

volumes:
  servervol:
    name: servervol
    driver: local
    driver_opts:
      type: none
      device: ./serverdata
      o: bind

  clientvol:
    name: clientvol
    driver: local
    driver_opts:
      type: none
      device: ./clientdata
      o: bind

networks:
  teht1network:
