version: "3"

services:
  server:
    # build the server image with dockerfile specs
    # when running docker-compose build
    # or docker-compose up
    build:
      context: ./server
    image: sakuexe/server-image
    env_file:
      - settings.env
    networks:
      - teht1network
    volumes:
      - servervol:/serverdata
    container_name: server
    command: ["sh", "-c", "node index.js"]

  client:
    # build the client image with dockerfile specs
    # when running docker-compose build
    # or docker-compose up
    build:
      context: ./client
    image: sakuexe/client-image
    env_file:
      - settings.env
    networks:
      - teht1network
    volumes:
      - clientvol:/clientdata
    container_name: client
    command: ["sh", "-c", "sleep 5 && node index.js"]

volumes:
  servervol:
    name: servervol
    driver: local
    driver_opts:
      type: none
      device: ./serverdata
      o: bind

  clientvol:
    name: clientvol
    driver: local
    driver_opts:
      type: none
      device: ./clientdata
      o: bind

networks:
  teht1network:
